function buildLeftPanel(fig)
%ROV.UI.BUILDLEFTPANEL  Construct the left control panel of the viewer.
%
% PURPOSE
%   Builds the INPUT FILES / VIEW SETTINGS / COLOUR / ACTIONS sections
%   of the left-hand column. All callbacks are wired to functions in
%   the rov.callbacks package so each control can be debugged in
%   isolation.
%
% INPUT
%   fig : handle to the main uifigure (fig.UserData already populated
%         by rov.initState and with empty panels created).
%
% SIDE EFFECTS
%   Populates the following handles in fig.UserData.h:
%     btnBrowseImg, btnBrowseAtlas, listImages, listAtlas,
%     ddView, numSpacing, numRows, numCols,
%     ddScheme, ddCmap, sldrAlpha, lblAlpha, lblCmapNote,
%     statusLbl
%
% EXAMPLE
%   rov.ui.buildLeftPanel(fig);
%
% See also: rov.ui.buildMiddlePanel, rov.ui.buildColorbarPanel,
%           rov.ui.buildRightPanel, rov.ui.uiTheme

    s = fig.UserData;
    C = rov.ui.uiTheme();

    g = uigridlayout(s.h.leftPanel, [26,1], ...
            'RowHeight', {16,25,65,25,65, 8, ...
                          16,25,25,25,    8, ...
                          16,25,25,28,16, 8, ...
                          16,28,28,28,28,28,30, 8,16}, ...
            'Padding',         [8 8 8 8], ...
            'RowSpacing',      3, ...
            'BackgroundColor', C.panel);

    % ---- INPUT FILES -------------------------------------------------
    rov.ui.secLbl(g, [C.glyph.bullet '  INPUT FILES'], C);

    s.h.btnBrowseImg = uibutton(g, 'push', ...
        'Text','Select Brain Images...', ...
        'BackgroundColor', C.btn, 'FontColor', C.text, ...
        'ButtonPushedFcn', @(~,~) rov.io.onBrowseImages(fig));

    s.h.listImages = uilistbox(g, ...
        'Items', rov.util.shortNames(s.imageNames), ...
        'Multiselect','off', ...
        'BackgroundColor', C.listbg, 'FontColor', C.text, 'FontSize', 9);

    s.h.btnBrowseAtlas = uibutton(g, 'push', ...
        'Text','Select Atlas File(s)...', ...
        'BackgroundColor', C.btn, 'FontColor', C.text, ...
        'ButtonPushedFcn', @(~,~) rov.io.onBrowseAtlas(fig));

    s.h.listAtlas = uilistbox(g, ...
        'Items', rov.util.shortNames(s.atlasNames), ...
        'Multiselect','off', ...
        'BackgroundColor', C.listbg, 'FontColor', C.text, 'FontSize', 9);

    rov.ui.spacer(g);

    % ---- VIEW SETTINGS ----------------------------------------------
    rov.ui.secLbl(g, [C.glyph.bullet '  VIEW SETTINGS'], C);

    r1 = rov.ui.sg(g, [1,2], {'fit','1x'}, C);
    uilabel(r1, 'Text','Plane:', 'FontColor', C.muted);
    s.h.ddView = uidropdown(r1, ...
        'Items', {'Transverse','Coronal','Sagittal'}, ...
        'Value', s.viewDir, ...
        'BackgroundColor', C.ctrl, 'FontColor', C.text, ...
        'ValueChangedFcn', @(~,~) rov.callbacks.onViewChanged(fig));

    r2 = rov.ui.sg(g, [1,2], {'fit','1x'}, C);
    uilabel(r2, 'Text','Spacing (mm):', 'FontColor', C.muted);
    s.h.numSpacing = uieditfield(r2, 'numeric', ...
        'Value', s.spacing, 'Limits', [0.5 200], ...
        'BackgroundColor', C.ctrl, 'FontColor', C.text, ...
        'ValueChangedFcn', @(~,~) rov.callbacks.onSpacingChanged(fig));

    r3 = rov.ui.sg(g, [1,4], {'fit','1x','fit','1x'}, C);
    uilabel(r3, 'Text','Rows:', 'FontColor', C.muted);
    s.h.numRows = uieditfield(r3, 'numeric', ...
        'Value', s.nRows, 'Limits', [1 20], ...
        'BackgroundColor', C.ctrl, 'FontColor', C.text, ...
        'ValueChangedFcn', @(~,~) rov.callbacks.onRowColChanged(fig));
    uilabel(r3, 'Text','Cols:', 'FontColor', C.muted);
    s.h.numCols = uieditfield(r3, 'numeric', ...
        'Value', s.nCols, 'Limits', [1 20], ...
        'BackgroundColor', C.ctrl, 'FontColor', C.text, ...
        'ValueChangedFcn', @(~,~) rov.callbacks.onRowColChanged(fig));

    rov.ui.spacer(g);

    % ---- COLOUR ------------------------------------------------------
    rov.ui.secLbl(g, [C.glyph.bullet '  COLOUR'], C);

    r4 = rov.ui.sg(g, [1,2], {'fit','1x'}, C);
    uilabel(r4, 'Text','Scheme:', 'FontColor', C.muted);
    s.h.ddScheme = uidropdown(r4, ...
        'Items', {'Continuous','Discrete'}, 'Value', s.colorScheme, ...
        'BackgroundColor', C.ctrl, 'FontColor', C.text, ...
        'ValueChangedFcn', @(~,~) rov.callbacks.onColorSchemeChanged(fig));

    r5 = rov.ui.sg(g, [1,2], {'fit','1x'}, C);
    uilabel(r5, 'Text','Colormap:', 'FontColor', C.muted);
    s.h.ddCmap = uidropdown(r5, ...
        'Items', {'parula','turbo','hot','jet','cool','winter','bone','gray','hsv'}, ...
        'Value', s.colormapName, ...
        'BackgroundColor', C.ctrl, 'FontColor', C.text, ...
        'ValueChangedFcn', @(~,~) rov.callbacks.onColormapChanged(fig));

    r6 = rov.ui.sg(g, [1,3], {'fit','1x',34}, C);
    uilabel(r6, 'Text','Alpha:', 'FontColor', C.muted);
    s.h.sldrAlpha = uislider(r6, 'Limits',[0 1], 'Value', s.alpha, ...
        'MajorTicks', [], 'MinorTicks', [], ...
        'ValueChangedFcn', @(src,~) rov.callbacks.onAlphaChanged(fig, src));
    s.h.lblAlpha = uilabel(r6, 'Text', sprintf('%.2f', s.alpha), ...
        'FontColor', C.text, 'HorizontalAlignment','right');

    s.h.lblCmapNote = uilabel(g, ...
        'Text','* Continuous: single atlas only', ...
        'FontColor', C.muted, 'FontSize', 9);

    rov.ui.spacer(g);

    % ---- ACTIONS -----------------------------------------------------
    rov.ui.secLbl(g, [C.glyph.bullet '  ACTIONS'], C);

    uibutton(g, 'push', 'Text','Refresh Display', ...
        'BackgroundColor', [0.16 0.38 0.16], ...
        'FontColor', C.text, 'FontWeight','bold', ...
        'ButtonPushedFcn', @(~,~) rov.callbacks.onRefresh(fig));

    uibutton(g, 'push', 'Text','Save Main Images...', ...
        'BackgroundColor', [0.28 0.20 0.40], 'FontColor', C.text, ...
        'ButtonPushedFcn', @(~,~) rov.io.saveMain(fig));

    uibutton(g, 'push', 'Text','Save Colorbar...', ...
        'BackgroundColor', [0.28 0.20 0.40], 'FontColor', C.text, ...
        'ButtonPushedFcn', @(~,~) rov.io.saveColorbar(fig));

    uibutton(g, 'push', 'Text','Save Legend...', ...
        'BackgroundColor', [0.28 0.20 0.40], 'FontColor', C.text, ...
        'ButtonPushedFcn', @(~,~) rov.io.saveLegend(fig));

    uibutton(g, 'push', 'Text','Save Full Window...', ...
        'BackgroundColor', [0.28 0.20 0.40], 'FontColor', C.text, ...
        'ButtonPushedFcn', @(~,~) rov.io.saveFull(fig));

    uibutton(g, 'push', ...
        'Text', [C.glyph.star ' Save All  [600 DPI]'], ...
        'BackgroundColor', [0.62 0.32 0.10], ...
        'FontColor', C.text, 'FontWeight','bold', ...
        'ButtonPushedFcn', @(~,~) rov.io.saveAll(fig));

    rov.ui.spacer(g);

    s.h.statusLbl = uilabel(g, ...
        'Text','Ready. Select files to begin.', ...
        'FontColor', C.muted, 'FontSize', 9, 'WordWrap','on', ...
        'VerticalAlignment','top');

    fig.UserData = s;
end
