function buildColorbarPanel(fig)
%ROV.UI.BUILDCOLORBARPANEL  Construct the colorbar column with custom limits.
%
% PURPOSE
%   Builds the colorbar column that sits between the image grid and the
%   ROI legend. Two numeric edit fields (Min / Max) let the user
%   override the auto-derived data range. They are only enabled in
%   Continuous + single-atlas mode; otherwise they are visually present
%   but disabled, and the colorbar shows a placeholder strip so the
%   main column width never reflows.
%
% INPUT
%   fig : main uifigure handle.
%
% SIDE EFFECTS
%   Populates fig.UserData.h.cbGrid, lblCbTitle, cbAx, numCbMax, numCbMin.
%
% LAYOUT (top to bottom, matching numerical reading order)
%   row 1 : "Colorbar" header label
%   row 2 : "Max" label
%   row 3 : Max edit field (placed above the colorbar)
%   row 4 : the colorbar axes itself (stretches)
%   row 5 : Min edit field (placed below the colorbar)
%   row 6 : "Min" label
%
% EXAMPLE
%   rov.ui.buildColorbarPanel(fig);

    s = fig.UserData;
    C = rov.ui.uiTheme();

    g = uigridlayout(s.h.cbPanel, [6,1], ...
        'RowHeight',       {20, 14, 24, '1x', 24, 14}, ...
        'Padding',         [6 8 6 8], ...
        'RowSpacing',      3, ...
        'BackgroundColor', [0.10 0.10 0.13]);
    s.h.cbGrid = g;

    s.h.lblCbTitle = uilabel(g, 'Text','Colorbar', ...
        'FontWeight','bold', 'FontColor', C.accent, ...
        'HorizontalAlignment','center');

    uilabel(g, 'Text','Max', ...
        'FontColor', C.muted, 'FontSize', 9, ...
        'HorizontalAlignment','center');

    s.h.numCbMax = uieditfield(g, 'numeric', ...
        'AllowEmpty',         true, ...
        'BackgroundColor',    C.ctrl, ...
        'FontColor',          C.text, ...
        'HorizontalAlignment','center', ...
        'Tooltip',            'Override colorbar max (clear field for auto)', ...
        'ValueDisplayFormat', '%.4g', ...
        'ValueChangedFcn',    @(~,~) rov.callbacks.onCbLimitsChanged(fig));

    s.h.cbAx = uiaxes(g, ...
        'BackgroundColor',[0.10 0.10 0.13], ...
        'XColor','none','YColor',[0.85 0.85 0.85],'Box','on');
    s.h.cbAx.Toolbar.Visible = 'off';
    rov.util.safeDisableInteractivity(s.h.cbAx);

    s.h.numCbMin = uieditfield(g, 'numeric', ...
        'AllowEmpty',         true, ...
        'BackgroundColor',    C.ctrl, ...
        'FontColor',          C.text, ...
        'HorizontalAlignment','center', ...
        'Tooltip',            'Override colorbar min (clear field for auto)', ...
        'ValueDisplayFormat', '%.4g', ...
        'ValueChangedFcn',    @(~,~) rov.callbacks.onCbLimitsChanged(fig));

    uilabel(g, 'Text','Min', ...
        'FontColor', C.muted, 'FontSize', 9, ...
        'HorizontalAlignment','center');

    % Start blank so they read as "auto" on a fresh viewer.
    s.h.numCbMax.Value  = [];
    s.h.numCbMin.Value  = [];
    s.h.numCbMax.Enable = 'off';
    s.h.numCbMin.Enable = 'off';

    fig.UserData = s;
end
