function palette = buildQualPalette(n)
%ROV.COMPUTE.BUILDQUALPALETTE  Qualitative palette of N visually distinct colours.
%
% PURPOSE
%   Returns N colours intended to be as distinguishable as possible.
%   The first 12 are hand-picked (ColorBrewer-style) so small atlases
%   look familiar; for N > 12 the remaining slots are generated by
%   walking the HSV hue axis with the golden-ratio increment, which
%   maximises perceptual spread for any N.
%
%   Used in Discrete single-atlas mode where every ROI gets a unique
%   colour (no graph-colouring reuse).
%
% INPUT
%   n : desired number of colours (>= 1).
%
% OUTPUT
%   palette : n x 3 RGB matrix in [0,1].
%
% NOTES
%   - For very large N (>200) some colour pairs will inevitably look
%     similar - there is no perceptually uniform palette of arbitrary
%     size. The legend tooltip shows the ROI name on hover so users can
%     still disambiguate.
%   - We alternate saturation and value so neighbouring hues do not
%     also share lightness, which improves distinguishability.
%
% EXAMPLE
%   p = rov.compute.buildQualPalette(116);   % AAL atlas

    FIXED = [0.894 0.102 0.110; 0.216 0.494 0.722; 0.302 0.686 0.290;
             0.596 0.306 0.639; 1.000 0.498 0.000; 0.996 0.922 0.122;
             0.651 0.337 0.157; 0.969 0.506 0.749; 0.188 0.627 0.694;
             0.400 0.761 0.647; 0.996 0.878 0.565; 0.600 0.600 0.600];

    if n <= size(FIXED, 1)
        palette = FIXED(1:n, :);
        return;
    end

    nX = n - size(FIXED, 1);

    % Golden-ratio hue increment ~= 0.6180339887; gives maximally
    % spread hues for any sequence length.
    phi  = (sqrt(5) - 1) / 2;
    hues = mod(0.13 + (0:nX-1)' * phi, 1);

    % Cycle saturation and value so adjacent entries differ in more
    % than just hue.
    sats = repmat([0.85; 0.60; 0.95; 0.70], ceil(nX/4), 1);  sats = sats(1:nX);
    vals = repmat([0.95; 0.75; 0.85; 0.65], ceil(nX/4), 1);  vals = vals(1:nX);

    palette = [FIXED; hsv2rgb([hues, sats, vals])];
end
